title: "Looking for Work"
author: "Gean Ramos"
email: "lookingwork@geanramos.com.br"
description: "descricao em breve"
permalink: ':title'
image: "https://d15k2d11r6t6rl.cloudfront.net/pub/bfra/mc32312m/m17/9r2/5eg/data-cta.png" #https://picsum.photos/600/363
avatar: "https://geanramos.com.br/img/avatar.png"
baseurl: ""
url: "https://geanme.github.io/"
theme: minima
markdown: kramdown
paginate: 10

# Dados institucionais
company:
  name: "OX Indústria de Produtos Químicos LTDA"
  address: "Rua Dois, nº 69 - Titanlândia - Castanhal/PA"
  cep: "CEP: 68741-492"
  website: "https://souox.com/"


